### ISSUE TITLE
conflicting with @typescript-eslint/adjacent-overload-signatures rule

### ISSUE THREAD

**Issue by luber** [seiyab/prettier-plugin-sort-members#49] opened 2024-08-19 17:55 UTC
getter and setters suppose to be kept together,  but it ends up with this order:
```
export class TestClass {
  get visible(): boolean {}
  get theme(): string {}
  set visible(_val: boolean) {}
}
```

expected:
```
export class TestClass {
  get visible(): boolean {}
  set visible(_val: boolean) {}

  get theme(): string {}
}
```

**Comment by seiyab** [comment] 2024-08-20 06:08
@luber Would you try 0.2.0 with `keepGettersAndSettersTogether: true`?

**Comment by luber** [comment] 2024-08-20 07:16
> @luber Would you try 0.2.0 with `keepGettersAndSettersTogether: true`?

Hi. Thanks for quick response. Unfortunately it does not work for me. I have recorded video were I tried to use new version with new option. My IDE is setup to run formatter on each save:
![2024-08-20_10-13-07 (1)](https://github.com/user-attachments/assets/5dcfb4c1-2ee6-4e15-b867-5f9011e72a99)

**Comment by seiyab** [comment] 2024-08-20 08:13
@luber 
Thank you for trying it and clear description with video.
Could you order getters and setters manually once? `keepGettersAndSettersTogether: true` just prevent existing paired getter / setter from split as of now.
I might improve it later to put getters and setters with same name together automatically. But it is somewhat hard because it looks to require completely new mechanism from current ordering.

**Comment by luber** [comment] 2024-08-20 08:27
@seiyab yes, manual sorting does the job.
Thank you for clarification and great plugin :)

**Comment by seiyab** [comment] 2024-08-20 10:15
Thank you for feedback.

If you can accept more opinionated order, `sortMembersAlphabetically` can help automatically put getter and setter with same name together.

**Comment by seiyab** [comment] 2024-09-18 13:46
@luber 
Would you try 0.2.1-rc.0? It will automagically couple setters with associated getters even without `sortMembersAlphabetically`.

**Comment by luber** [comment] 2024-09-18 19:01
> @luber Would you try 0.2.1-rc.0? It will automagically couple setters with associated getters even without `sortMembersAlphabetically`.

Hello, I have installed the latest version:
`"prettier-plugin-sort-members": "^0.2.1-rc.0"`

in `.prettierrc` I don't have `sortMembersAlphabetically` option specified, only `"keepGettersAndSettersTogether": true`

Unfortunately, when I tried to save changes in test class - the getters and setters were **not** grouped together:
![2024-09-18_22-00-11 (1)](https://github.com/user-attachments/assets/98f4dcd5-8f00-44e7-92f3-9699d878d82c)

**Comment by seiyab** [comment] 2024-09-18 20:54
Hmm... Sorry, I'll investigate it. Thank you for reporting the result 🙌

**Comment by seiyab** [comment] 2024-09-18 21:26
@luber 
I reproduced similar behavior on my VSCode and `Developer: Reload Window` fixed the problem. Would you try reloading your IDE?
If it even doesn't work, I'd like to see the output for `npx prettier path/to/test-class.ts`. Thanks.

**Comment by luber** [comment] 2024-09-19 08:56
@seiyab I can confirm that restarting IDE did the trick :) Now it sorted correctly.
The output of `npx prettier test-class.ts`:
```
export class Foo {
  constructor() {}

  get menuMode(): string {
    return 'mode1';
  }

  set menuMode(value: string) {
    console.log('menuMode', value);
  }
  get theme(): string {
    return 'dark';
  }
}
```

Would be nice to have an empty line before `get theme(): string {`...

Before running prettier it had one:
```
export class Foo {
  constructor() {}

  get menuMode(): string {
    return 'mode1';
  }
  
  get theme(): string {
    return 'dark';
  }

  set menuMode(value: string) {
    console.log('menuMode', value);
  }
}
```

**Comment by seiyab** [comment] 2024-09-19 21:59
@luber Nice 👍 

> Would be nice to have an empty line before get theme(): string {

It looks hard. [Prettier itself tries to preserve empty line](https://prettier.io/docs/en/rationale.html#empty-lines). And for class members, actually [it preserves empty line that follows it](https://github.com/prettier/prettier/blob/8f33827a5c005f3d701b2bfcbc24ee3539e0e777/src/language-js/print/class.js#L290-L292). For the input, `set menuMode(value: string)` doesn't have empty line below. So the resulting code neither have empty line after `set menuMode(value: string)`.
FYI, when you add empty line after `set menuMode(value: string)`, Prettier won't strip it.

**Comment by seiyab** [comment] 2024-09-19 22:05
Anyway, I close this issue as resolved since the original problem is solved.

If you want better empty line behavior, open a new issue. It looks very hard but I might study ways to hack Prettier if you give me ideas and justification. I'd like to get this plugin prettier.

**Closed as completed by seiyab** 2024-09-19 22:05 UTC
